{"name": "Обновление данных с неверным токеном", "status": "passed", "start": 1757793078943, "stop": 1757793079024, "uuid": "f340ddfe-c64f-4e64-b132-17d251719be3", "historyId": "b54bdc01c7d54a5ef7e256fa3cee234b", "testCaseId": "b54bdc01c7d54a5ef7e256fa3cee234b", "fullName": "tests.test_user_update.TestUserUpdate#test_update_with_invalid_token", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_update"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "mbp-eberendeeva-OZON-LV7CJ66N3T"}, {"name": "thread", "value": "19269-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_update"}]}